### ISSUE TITLE
Checklist pre-presentación

### ISSUE THREAD

**Issue by elias-garcia** [AgoraBinaria/eduhostalaria#22]
- [x] data `datepicker` e turno `radiobutton` do evento
- [x] nome de evento opcional
- [ ] Incluir los precios y el aforo de la oferta, proveniente de la organización.
obtener el usuario `security.getMe()` y después la organization `me.getAdministratedOrganization(user.organizationId)`

- [x] Eliminar el campo 'nombre' del formulario crear evento.
- [x] Juntar los campos 'hora' y 'fecha' en el formulario de crear evento.
- [x] Añadir botón de editar evento en el editor de eventos.
- [x] Añadir botón de reservar evento en el listado de los eventos de un centro.
- [x] Cambiar el icono de los eventos por 'icon-time'.
